name: "X0F5C3 Automatic Releases"
description: "Creates a new git tag when the version field in the root cobra.Command is changed."
author: "x0f5c3"
branding:
  icon: award
  color: orange
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.myInput }}
